<?php

use Magento\Framework\View\Element\Template;
use Koen\AcademyBlogFrontend\ViewModel\LatestPosts;

/** @var Template $block */
/** @var LatestPosts $viewModel */
$viewModel = $block->getViewModel();
$maxPosts = (int)$block->getMaxPosts();

$blogPosts = $viewModel->getBlogPosts($maxPosts);
?>
<div>
    <?php foreach ($blogPosts as $blogPost) : ?>
        <h2><?= $blogPost->getTitle() ?></h2>
        <p><?= $blogPost->getBody() ?></p>
    <?php endforeach; ?>
</div>
